name = "globalhot"
pages_build_output_dir = "dist"
compatibility_date = "2026-07-18"

[[d1_databases]]
binding = "DB"
database_name = "globalhot-recommendations"
database_id = "866c176d-9335-4545-b21f-2eff64c044cb"
migrations_dir = "migrations"
