import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { getRecommendations, postRecommendation } from '../functions/_lib/recommendations.js';

function mockDb() {
  const models = new Map([['luna-miro', { id: 'luna-miro', baseRecommendations: 284, status: 'active' }]]);
  const votes = []; const inserts = [];
  return { votes, inserts, prepare(sql) { let bound = []; const statement = { bind(...args) { bound = args; return statement; }, async all() { return { results: [...models.values()].map((m) => ({ modelId: m.id, count: m.baseRecommendations + votes.filter((v) => v.model_id === m.id).length })) }; }, async first() { if (sql.includes('FROM models WHERE')) { const m = models.get(bound[0]); return m?.status === bound[1] ? m : null; } if (sql.includes('voter_hash = ?')) return { count: votes.filter((v) => v.voter_hash === bound[0] && v.created_at >= bound[1]).length }; const m = models.get(bound[0]); return m && { count: m.baseRecommendations + votes.filter((v) => v.model_id === m.id).length }; }, async run() { const [model_id, voter_hash, created_at] = bound; inserts.push([...bound]); if (votes.some((v) => v.model_id === model_id && v.voter_hash === voter_hash)) return { meta: { changes: 0 } }; votes.push({ model_id, voter_hash, created_at }); return { meta: { changes: 1 } }; } }; return statement; } };
}
const GOOD_SALT = 'this-is-a-test-only-salt-with-at-least-32-characters';
function ctx(db, { salt = GOOD_SALT, headers, url = 'http://localhost/api/recommendations/luna-miro' } = {}) { return { env: db ? { DB: db, ...(salt ? { RECOMMENDATION_SALT: salt } : {}) } : {}, request: new Request(url, { method: 'POST', headers }) }; }

test('missing DB and GET use structured response and safe active counts', async () => { const missing = await getRecommendations(ctx()); assert.equal(missing.status, 503); assert.equal((await missing.json()).error.code, 'service_unavailable'); const r = await getRecommendations(ctx(mockDb())); assert.equal(r.status, 200); assert.equal(r.headers.get('cache-control'), 'no-store'); assert.deepEqual((await r.json()).models, [{ modelId: 'luna-miro', count: 284 }]); });
test('POST rejects invalid, cross-origin, unavailable secrets, production IP gaps, and unknown models', async () => { const db = mockDb(); assert.equal((await postRecommendation(ctx(db), 'bad id')).status, 400); assert.equal((await postRecommendation(ctx(db, { headers: { Origin: 'https://evil.example' } }), 'luna-miro')).status, 403); const shortSalt = await postRecommendation(ctx(db, { salt: 'too-short' }), 'luna-miro'); assert.equal(shortSalt.status, 503); assert.equal((await shortSalt.json()).error.code, 'service_unavailable'); assert.equal((await postRecommendation(ctx(db, { url: 'https://site.example/api/recommendations/luna-miro' }), 'luna-miro')).status, 503); assert.equal((await postRecommendation(ctx(db), 'unknown')).status, 404); });
test('POST succeeds once, returns duplicate count, rate-limits, and stores only hash', async () => { const db = mockDb(); const options = { headers: { 'X-Forwarded-For': '203.0.113.77', 'User-Agent': 'unique-agent' } }; const success = await postRecommendation(ctx(db, options), 'luna-miro'); assert.deepEqual(await success.json(), { ok: true, model: { modelId: 'luna-miro', count: 285 }, recommended: true }); const duplicate = await postRecommendation(ctx(db, options), 'luna-miro'); assert.equal(duplicate.status, 409); assert.deepEqual((await duplicate.json()).model, { modelId: 'luna-miro', count: 285 }); assert.match(db.inserts[0][1], /^[a-f0-9]{64}$/); assert.equal(db.inserts[0].join('|').includes('203.0.113.77'), false); assert.equal(db.inserts[0].join('|').includes('unique-agent'), false); const original = db.prepare.bind(db); db.prepare = (sql) => { const s = original(sql); if (sql.includes('voter_hash = ?')) s.first = async () => ({ count: 20 }); return s; }; assert.equal((await postRecommendation(ctx(db, { url: 'https://site.example/api/recommendations/luna-miro', headers: { 'CF-Connecting-IP': '198.51.100.1' } }), 'luna-miro')).status, 429); });
test('migration has six demo seeds, categories, unique vote identity and indexes', async () => { const sql = await readFile(new URL('../migrations/0001_recommendations.sql', import.meta.url), 'utf8'); for (const id of ['luna-miro', 'hana-velvet', 'aria-nova', 'mio-rey', 'noa-citrine', 'sora-ki']) assert.match(sql, new RegExp(`'${id}'`)); for (const category of ['model', 'gravure', 'cosplay']) assert.match(sql, new RegExp(`'${category}'`)); assert.match(sql, /, 1, 'active'/); assert.match(sql, /UNIQUE \(model_id, voter_hash\)/); assert.match(sql, /idx_recommendation_votes_model_id/); assert.match(sql, /idx_recommendation_votes_voter_hash_created_at/); });
