name = "globalhot-cron"
main = "worker.js"
compatibility_date = "2024-09-23"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "SUMMARY_KV"
id = "e819959613044e8ca4998aa4d4ec69bd"

[triggers]
crons = ["0 */6 * * *"]
