export const QUIZ_FIRST_DATE = '2026-07-18';

export const ALLOWED_QUIZ_FACT_IDS = new Set([
  'vix-near-term-volatility',
  'cpi-basket-index',
  'unemployment-labor-force',
  'gdp-final-output',
  'fed-funds-overnight',
  'treasury-par-yield-curve',
  'cpi-index-vs-rate',
  'vix-not-direction',
  'fed-rate-chain',
  'cpi-percent-change',
  'cpi-seasonal-adjustment',
  'gdp-import-subtraction',
  'unemployment-u3',
  'yield-curve-comparison',
  'vix-data-delay',
  'fomc-primary-materials',
  'cpi-period-check',
  'gdp-estimate-vintage',
  'treasury-same-date',
  'unemployment-frequency',
  'bok-date-unit-check',
]);
